security:

    encoders:
        #Symfony\Component\Security\Core\User\User: plaintext
        AppBundle\Entity\User:
            algorithm: bcrypt

    providers:
        dbal:
            entity:
                class: AppBundle:User
                #property: email

    role_hierarchy:
        ROLE_COMMERCIAL: [ROLE_FINAL_CLIENT]
        ROLE_TECHNICIAN: [ROLE_FINAL_CLIENT]
        ROLE_PROJECT_RESP: [ROLE_TECHNICIAN, ROLE_COMMERCIAL]
        ROLE_ADMIN: [ROLE_PROJECT_RESP]
        ROLE_SUPER_ADMIN: [ROLE_ADMIN]

    firewalls:
        dev:
            anonymous: ~
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            pattern: ^/
            user_checker: app.user_checker
            remember_me:
                secret: '%secret%'
                lifetime: 604800
                path: /
            anonymous: ~
            provider: dbal
            form_login:
                login_path: login
                check_path: login
                default_target_path: default_security_target
                #failure_path: login_failure

                #csrf token options
                #csrf_parameter: _csrf_token
                #csrf_token_id: authenticate
                #csrf_token_generator: security.csrf.token_manager
            logout:
                path: /logout
                target: /

    access_control:
        - { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY}
        - { path: ^/reset, roles: IS_AUTHENTICATED_ANONYMOUSLY}
        - { path: ^/dashboard, roles: IS_AUTHENTICATED_REMEMBERED}
        #- { path: ^/, roles: ROLE_ADMIN }
